### ISSUE TITLE
Firedrake installation broken

### ISSUE THREAD

**Issue by salazardetroya** [fem-on-colab/fem-on-colab#12]
Hi Francesco,

Thanks a lot for putting these scripts together! I was trying to use Firedrake on colab, but the installation is currently broken due to a change in pytools two days ago: https://github.com/inducer/pytools/commit/ed94f3a15d37618d17e10e8e49299244f8a8a61a I think it might have to do with the python version in colab.

**Comment by francesco-ballarin** [comment]
I can confirm that the installation is currently broken after the automated weekly build that was run tonight. 

Manually shipping typing-extensions 4.1.1 alongside firedrake will probably fix this, I will have a look later. In the meantime, can you try doing a `pip3 install --upgrade typing-extensions` in your colab instance to see if that fix would work?

**Comment by salazardetroya** [comment]
That works, thanks!

**Comment by francesco-ballarin** [comment]
The issue is fixed on the newly released firedrake package. Thanks for reporting the issue so quickly!
