### ISSUE TITLE
.bp file cannot be viewed in paraview 

### ISSUE THREAD

**Issue by neolam1987** [fem-on-colab/fem-on-colab#26]
i used google colab to run FEM using dolfinx tutorial by Jørgen S. Dokken with updated version on v0.6.0.
https://github.com/jorgensd/dolfinx-tutorial/blob/v0.4.0/chapter2/ns_code2.ipynb.

However, the .bp file generated could not be viewed in paraview.

the issue was reported to fenics project discourse group
[Link](https://fenicsproject.discourse.group/t/bp-file-cannot-be-viewed-in-paraview/11655/1)

They suggest it is because for google colab PR

```
try:
    import dolfinx
except ImportError:
    !wget "https://fem-on-colab.github.io/releases/fenicsx-install-real.sh" -O "/tmp/fenicsx-install.sh" && bash "/tmp/fenicsx-install.sh"
    import dolfinx
```

PR mentioned above did not add the optional argument to the python layer.

Please see if it is the case and help resolve, many thanks.

**Comment by francesco-ballarin** [comment]
The issue is in dolfinx, not in FEM on Colab.
