### ISSUE TITLE
NGSolve PML Tutorial crashes kernel

### ISSUE THREAD

**Issue by j-1git** [fem-on-colab/fem-on-colab#6]
[https://ngsolve.org/docu/latest/i-tutorials/unit-1.7-helmholtz/pml.html](url)

I'm trying to run the above Tutorial from the NGSolve documentation. The kernel crashes when assembling the bilinearform `a` .  The linear from `b` assembles without issue.  Other tutorials that don't use the `mesh.SetPML()` function run without issue.

**Comment by francesco-ballarin** [comment]
Hi @NGsolve team,
is there any way to increase the verbosity of the assembly process? That might help me in tracking down why assembly without PML works, while the issue reported by @j-1git  appears when `mesh.SetPML()` is used.

Thanks!

**Comment by j-1git** [comment]
I increased 'verbosity of the assembly process' by increasing the `msg_level`
`ngsglobals.msg_level=7`

Definition for `msg_level` at line 106 in [https://github.com/NGSolve/ngsolve/blob/master/comp/python_comp.cpp](url)

There may be another way to increase messaging. I'm new to both Ngsolve and Colab.

The output from the Google Colab app.log

<html>
<body>


Oct 3, 2021, 10:58:56 AM | WARNING | WARNING:root:kernel ee1d7a47-1f7d-40f9-b8d4-f54374324da0 restarted
-- | -- | --
Oct 3, 2021, 10:58:56 AM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Oct 3, 2021, 10:58:53 AM | WARNING | switching to scalar evaluation
Oct 3, 2021, 10:58:53 AM | WARNING | PML-trafo operator() (SIMD_IntegrationRule & ir) not overloaded
Oct 3, 2021, 10:58:53 AM | WARNING | switching to scalar evaluation
Oct 3, 2021, 10:58:53 AM | WARNING | PML-trafo operator() (SIMD_IntegrationRule & ir) not overloaded
Oct 3, 2021, 10:58:53 AM | WARNING | assemble VOL element 1320/1320
Oct 3, 2021, 10:58:53 AM | WARNING | switching back to standard evaluation
Oct 3, 2021, 10:58:53 AM | WARNING | PML-trafo operator() (SIMD_IntegrationRule & ir) not overloaded
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | same diffops:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | symmetric:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros_proxies:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros_deriv:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros:
Oct 3, 2021, 10:58:52 AM | WARNING | element-wise constant = 0
Oct 3, 2021, 10:58:52 AM | WARNING | 1: 1
Oct 3, 2021, 10:58:52 AM | WARNING | cumulated trial_proxy dims 0: 0
Oct 3, 2021, 10:58:52 AM | WARNING | 1: 1
Oct 3, 2021, 10:58:52 AM | WARNING | cumulated test_proxy dims 0: 0
Oct 3, 2021, 10:58:52 AM | WARNING | num trial_proxies 1
Oct 3, 2021, 10:58:52 AM | WARNING | num test_proxies 1
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | same diffops:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | symmetric:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros_proxies:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros_deriv:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros:
Oct 3, 2021, 10:58:52 AM | WARNING | element-wise constant = 1
Oct 3, 2021, 10:58:52 AM | WARNING | 1: 1
Oct 3, 2021, 10:58:52 AM | WARNING | cumulated trial_proxy dims 0: 0
Oct 3, 2021, 10:58:52 AM | WARNING | 1: 1
Oct 3, 2021, 10:58:52 AM | WARNING | cumulated test_proxy dims 0: 0
Oct 3, 2021, 10:58:52 AM | WARNING | num trial_proxies 1
Oct 3, 2021, 10:58:52 AM | WARNING | num test_proxies 1
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | same diffops:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | symmetric:
Oct 3, 2021, 10:58:52 AM | WARNING | 1
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros_proxies:
Oct 3, 2021, 10:58:52 AM | WARNING | 0 1
Oct 3, 2021, 10:58:52 AM | WARNING | 1 0
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros_deriv:
Oct 3, 2021, 10:58:52 AM | WARNING | 0 1
Oct 3, 2021, 10:58:52 AM | WARNING | 1 0
Oct 3, 2021, 10:58:52 AM | WARNING | nonzeros:
Oct 3, 2021, 10:58:52 AM | WARNING | element-wise constant = 1
Oct 3, 2021, 10:58:52 AM | WARNING | 1: 2
Oct 3, 2021, 10:58:52 AM | WARNING | cumulated trial_proxy dims 0: 0
Oct 3, 2021, 10:58:52 AM | WARNING | 1: 2
Oct 3, 2021, 10:58:52 AM | WARNING | cumulated test_proxy dims 0: 0
Oct 3, 2021, 10:58:52 AM | WARNING | num trial_proxies 1
Oct 3, 2021, 10:58:52 AM | WARNING | num test_proxies 1
Oct 3, 2021, 10:58:52 AM | WARNING | set global mesh
Oct 3, 2021, 10:58:52 AM | WARNING | Curving faces
Oct 3, 2021, 10:58:52 AM | WARNING | Curving edges
Oct 3, 2021, 10:58:52 AM | WARNING | Update clusters
Oct 3, 2021, 10:58:52 AM | WARNING | Curve elements, order = 3
Oct 3, 2021, 10:58:52 AM | WARNING | Update clusters
Oct 3, 2021, 10:58:52 AM | WARNING | Update faces
Oct 3, 2021, 10:58:52 AM | WARNING | Update edges
Oct 3, 2021, 10:58:52 AM | WARNING | Update mesh topology
Oct 3, 2021, 10:58:52 AM | WARNING | set global mesh
Oct 3, 2021, 10:58:52 AM | WARNING | Smoothing
Oct 3, 2021, 10:58:52 AM | WARNING | Combine improve
Oct 3, 2021, 10:58:52 AM | WARNING | Split improve
Oct 3, 2021, 10:58:52 AM | WARNING | Smoothing
Oct 3, 2021, 10:58:52 AM | WARNING | Edgeswapping, metric
Oct 3, 2021, 10:58:52 AM | WARNING | Smoothing
Oct 3, 2021, 10:58:52 AM | WARNING | Combine improve
Oct 3, 2021, 10:58:52 AM | WARNING | Split improve
Oct 3, 2021, 10:58:52 AM | WARNING | Smoothing
Oct 3, 2021, 10:58:52 AM | WARNING | Edgeswapping, metric
Oct 3, 2021, 10:58:52 AM | WARNING | Smoothing
Oct 3, 2021, 10:58:52 AM | WARNING | Combine improve
Oct 3, 2021, 10:58:52 AM | WARNING | Split improve
Oct 3, 2021, 10:58:52 AM | WARNING | Smoothing
Oct 3, 2021, 10:58:52 AM | WARNING | Edgeswapping, topological
Oct 3, 2021, 10:58:52 AM | WARNING | Surface meshing done
Oct 3, 2021, 10:58:52 AM | WARNING | Meshing domain 2 / 2
Oct 3, 2021, 10:58:52 AM | WARNING | Surface meshing done
Oct 3, 2021, 10:58:52 AM | WARNING | load internal triangle rules
Oct 3, 2021, 10:58:52 AM | WARNING | Meshing domain 1 / 2
Oct 3, 2021, 10:58:52 AM | WARNING | CalcLocalH: 152 Points 0 Elements 0 Surface Elements
Oct 3, 2021, 10:58:52 AM | WARNING | Boundary mesh done, np = 152
Oct 3, 2021, 10:58:52 AM | WARNING | Generate Mesh from spline geometry
Oct 3, 2021, 10:58:52 AM | WARNING | set global mesh
Oct 3, 2021, 10:58:52 AM | WARNING | importing NGSolve-6.2.2102-264-g4a2daaef3
Oct 3, 2021, 10:57:07 AM | INFO | Adapting to protocol v5.1 for kernel ee1d7a47-1f7d-40f9-b8d4-f54374324da0
Oct 3, 2021, 10:57:05 AM | INFO | Kernel started: ee1d7a47-1f7d-40f9-b8d4-f54374324da0
Oct 3, 2021, 10:54:00 AM | INFO | Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).


</body>
</html>

**Comment by francesco-ballarin** [comment]
Hi, I have further investigated a bit this issue.

I believe that the kernel is crashing because of [this line](https://github.com/NGSolve/ngsolve/blob/491b7337d69d5db58b17ef488ae145133e0d7501/fem/symbolicintegrator.cpp#L1635) which, to me, following the two commented lines below, looks like the code should call the same method but after switching off `simd_evaluate`.

Who is responsible of catching that exception?

I'd like to understand if this error handling is the issue here, because we have had problems with catching exceptions before (see e.g. #1 and #2).

EDIT: turned out to be wrong, see next post.

**Comment by francesco-ballarin** [comment]
This is the stack trace of the crash

```
#0  0x00007fe57d44660a in ngfem::ElementTransformation::UserDataStack::UserDataStack (atrafo=..., this=<synthetic pointer>) at /tmp/ngsolve-src/fem/elementtransformation.hpp:188
#1  ngfem::ElementTransformation::PushUserData (this=0x0) at /tmp/ngsolve-src/fem/elementtransformation.hpp:199
#2  ngfem::SymbolicBilinearFormIntegrator::T_CalcElementMatrixAdd<double, double, double> (this=this@entry=0x55a5e1afc890, fel=..., trafo=..., elmat=..., symmetric_so_far=@0x55a5e1e14120: false, lh=...) at /tmp/ngsolve-src/fem/symbolicintegrator.cpp:1358
#3  0x00007fe57c5bfa8d in ngfem::SymbolicBilinearFormIntegrator::CalcElementMatrix (this=0x55a5e1afc890, fel=..., trafo=..., elmat=..., lh=...) at /tmp/ngsolve-src/fem/symbolicintegrator.cpp:1825
#4  0x00007fe57f005c05 in ngcomp::S_BilinearForm<double>::DoAssemble(ngcore::LocalHeap&)::{lambda(ngcomp::FESpace::Element, ngcore::LocalHeap&)#2}::operator()(ngcomp::FESpace::Element, ngcore::LocalHeap&) const (__closure=0x55a5e00292e0, lh=..., el=..., el=...) at /tmp/ngsolve-src/comp/bilinearform.cpp:1501
#5  0x00007fe57f008d46 in std::__invoke_impl<void, ngcomp::S_BilinearForm<double>::DoAssemble(ngcore::LocalHeap&)::{lambda(ngcomp::FESpace::Element, ngcore::LocalHeap&)#2}&, ngcomp::FESpace::Element, ngcore::LocalHeap&>(std::__invoke_other, ngcomp::S_BilinearForm<double>::DoAssemble(ngcore::LocalHeap&)::{lambda(ngcomp::FESpace::Element, ngcore::LocalHeap&)#2}&, ngcomp::FESpace::Element&&, ngcore::LocalHeap&) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#6  std::__invoke_r<void, ngcomp::S_BilinearForm<double>::DoAssemble(ngcore::LocalHeap&)::{lambda(ngcomp::FESpace::Element, ngcore::LocalHeap&)#2}&, ngcomp::FESpace::Element, ngcore::LocalHeap&>(ngcomp::S_BilinearForm<double>::DoAssemble(ngcore::LocalHeap&)::{lambda(ngcomp::FESpace::Element, ngcore::LocalHeap&)#2}&, ngcomp::FESpace::Element&&, ngcore::LocalHeap&) (__fn=...) at /usr/include/c++/11/bits/invoke.h:111
#7  std::_Function_handler<void (ngcomp::FESpace::Element, ngcore::LocalHeap&), ngcomp::S_BilinearForm<double>::DoAssemble(ngcore::LocalHeap&)::{lambda(ngcomp::FESpace::Element, ngcore::LocalHeap&)#2}>::_M_invoke(std::_Any_data const&, ngcomp::FESpace::Element&&, ngcore::LocalHeap&) (__functor=..., __args#0=..., __args#1=...) at /usr/include/c++/11/bits/std_function.h:291
#8  0x00007fe57f050c69 in std::function<void (ngcomp::FESpace::Element, ngcore::LocalHeap&)>::operator()(ngcomp::FESpace::Element, ngcore::LocalHeap&) const (__args#1=..., __args#0=..., this=<optimized out>) at /usr/include/c++/11/bits/std_function.h:560
#9  operator() (r=..., __closure=0x55a5e1b13cd0) at /tmp/ngsolve-src/comp/fespace.cpp:1795
#10 operator() (ti=..., ti=..., __closure=0x55a5e1b13cc0) at /usr/local/include/core/taskmanager.hpp:239
#11 std::__invoke_impl<void, ngcore::ParallelForRange<long unsigned int, ngcomp::IterateElements(const ngcomp::FESpace&, ngfem::VorB, ngcore::LocalHeap&, const std::function<void(ngcomp::FESpace::Element, ngcore::LocalHeap&)>&)::<lambda(ngcore::IntRange)> >(ngcore::T_Range<long unsigned int>, ngcomp::IterateElements(const ngcomp::FESpace&, ngfem::VorB, ngcore::LocalHeap&, const std::function<void(ngcomp::FESpace::Element, ngcore::LocalHeap&)>&)::<lambda(ngcore::IntRange)>, int, ngcore::TotalCosts)::<lambda(ngcore::TaskInfo&)>&, ngcore::TaskInfo&> (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#12 std::__invoke_r<void, ngcore::ParallelForRange<long unsigned int, ngcomp::IterateElements(const ngcomp::FESpace&, ngfem::VorB, ngcore::LocalHeap&, const std::function<void(ngcomp::FESpace::Element, ngcore::LocalHeap&)>&)::<lambda(ngcore::IntRange)> >(ngcore::T_Range<long unsigned int>, ngcomp::IterateElements(const ngcomp::FESpace&, ngfem::VorB, ngcore::LocalHeap&, const std::function<void(ngcomp::FESpace::Element, ngcore::LocalHeap&)>&)::<lambda(ngcore::IntRange)>, int, ngcore::TotalCosts)::<lambda(ngcore::TaskInfo&)>&, ngcore::TaskInfo&> (__fn=...) at /usr/include/c++/11/bits/invoke.h:111
#13 std::_Function_handler<void(ngcore::TaskInfo&), ngcore::ParallelForRange<long unsigned int, ngcomp::IterateElements(const ngcomp::FESpace&, ngfem::VorB, ngcore::LocalHeap&, const std::function<void(ngcomp::FESpace::Element, ngcore::LocalHeap&)>&)::<lambda(ngcore::IntRange)> >(ngcore::T_Range<long unsigned int>, ngcomp::IterateElements(const ngcomp::FESpace&, ngfem::VorB, ngcore::LocalHeap&, const std::function<void(ngcomp::FESpace::Element, ngcore::LocalHeap&)>&)::<lambda(ngcore::IntRange)>, int, ngcore::TotalCosts)::<lambda(ngcore::TaskInfo&)> >::_M_invoke(const std::_Any_data &, ngcore::TaskInfo &) (__functor=..., __args#0=...) at /usr/include/c++/11/bits/std_function.h:291
#14 0x00007fe58fdf541d in std::function<void (ngcore::TaskInfo&)>::operator()(ngcore::TaskInfo&) const (__args#0=..., this=0x7ffc64e0d930) at /usr/include/c++/11/bits/std_function.h:560
#15 ngcore::TaskManager::CreateJob(std::function<void (ngcore::TaskInfo&)> const&, int) (afunc=..., antasks=antasks@entry=1) at /tmp/netgen-src/libsrc/core/taskmanager.cpp:307
#16 0x00007fe57f0515e7 in ngcore::ParallelForRange<long unsigned int, ngcomp::IterateElements(const ngcomp::FESpace&, ngfem::VorB, ngcore::LocalHeap&, const std::function<void(ngcomp::FESpace::Element, ngcore::LocalHeap&)>&)::<lambda(ngcore::IntRange)> > (costs=..., antasks=1, f=..., r=...) at /usr/local/include/core/taskmanager.hpp:236
#17 ngcomp::IterateElements(ngcomp::FESpace const&, ngfem::VorB, ngcore::LocalHeap&, std::function<void (ngcomp::FESpace::Element, ngcore::LocalHeap&)> const&) (fes=..., vb=<optimized out>, clh=..., func=...) at /tmp/ngsolve-src/comp/fespace.cpp:1781
#18 0x00007fe57eff1fff in ngcomp::S_BilinearForm<double>::DoAssemble (this=0x55a5e1b1b100, clh=...) at /usr/include/c++/11/bits/shared_ptr_base.h:1290
#19 0x00007fe57ef8fee3 in ngcomp::BilinearForm::Assemble (this=0x55a5e1b1b100, lh=...) at /tmp/ngsolve-src/comp/bilinearform.cpp:732
#20 0x00007fe57f59f22d in operator() (__closure=<optimized out>, reallocate=false, self=...) at /tmp/ngsolve-src/comp/python_comp.cpp:2481
#21 pybind11::detail::argument_loader<std::shared_ptr<ngcomp::BilinearForm>, bool>::call_impl<std::shared_ptr<ngcomp::BilinearForm>, ExportNgcomp(pybind11::module&)::<lambda(std::shared_ptr<ngcomp::BilinearForm>, bool)>&, 0, 1, pybind11::gil_scoped_release> (f=..., this=0x7ffc64e0e020) at /usr/local/include/pybind11/cast.h:1164
#22 pybind11::detail::argument_loader<std::shared_ptr<ngcomp::BilinearForm>, bool>::call<std::shared_ptr<ngcomp::BilinearForm>, pybind11::gil_scoped_release, ExportNgcomp(pybind11::module&)::<lambda(std::shared_ptr<ngcomp::BilinearForm>, bool)>&> (f=..., this=0x7ffc64e0e020) at /usr/local/include/pybind11/cast.h:1136
#23 operator() (__closure=0x0, call=...) at /usr/local/include/pybind11/pybind11.h:193
#24 _FUN () at /usr/local/include/pybind11/pybind11.h:171
#25 0x00007fe57f28236e in pybind11::cpp_function::dispatcher (self=<optimized out>, args_in=0x7fe591453c90, kwargs_in=0x0) at /usr/local/include/pybind11/pybind11.h:768
#26 0x000055a5dd4fc098 in _PyObject_FastCallKeywords ()
#27 0x000055a5dd56f4d9 in _PyEval_EvalFrameDefault ()
#28 0x000055a5dd5699ee in _PyEval_EvalCodeWithName ()
#29 0x000055a5dd5696f3 in PyEval_EvalCode ()
#30 0x000055a5dd6334c2 in ?? ()
#31 0x000055a5dd63383d in PyRun_FileExFlags ()
#32 0x000055a5dd6336e6 in PyRun_SimpleFileExFlags ()
#33 0x000055a5dd60b163 in ?? ()
#34 0x000055a5dd60ae0c in _Py_UnixMain ()
#35 0x00007fe5920b0bf7 in __libc_start_main (main=0x55a5dd4f7db0 <main>, argc=2, argv=0x7ffc64e0e938, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc64e0e928) at ../csu/libc-start.c:310
#36 0x000055a5dd60acea in _start ()
```

Note to future self: to obtain it without making Colab kernel crash I created a standalone python file `test.py` with the code, and run it in a notebook cell with
```
!gdb -batch -ex r -ex bt -args python3 test.py
```

The same code works as expected when disabling `LD_PRELOAD`
```
!LD_PRELOAD="" gdb -batch -ex r -ex bt -args python3 test.py
```
which suggest that this may be related to #1 and #3.

**Comment by francesco-ballarin** [comment]
Hi @j-1git 
the ngsolve package has been updated and now the MPL tutorial works correctly.

I have added it to our tests, see https://colab.research.google.com/github/fem-on-colab/fem-on-colab/blob/main/ngsolve/test-ngsolve-mpl.ipynb

Feel free to reopen if this does not solve the issue with your code.
